esphome:
  name: esp32s
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
    source:
      type: local
      path: ./my_components
    
switch:

api:

blinker:
  id: my_blinker
  pin: GPIO2
  name: "Blinker Control"

web_server:
  port: 80

wifi:
  ssid: "vuDevices"
  password: "Acorn1873"

  ap:
    ssid: "Esp32S Fallback Hotspot"
    password: "1pGSAMI5OktC"

